### ISSUE TITLE
Checklist for 6.0.0

### ISSUE THREAD

**Issue by smoelius** [trailofbits/test-fuzz#352]
- [x] Remove deprecated options (#340)
- [x] Make `self_ty_in_module_name` the default behavior (#328 and #379)
- [x] Remove CBOR formats (1d0aab539e1a9947eb4a3d049c495fab0d24244e)
- [x] Make `--no-instrumentation` the default (#380)
- [x] Make `--pretty` an alias for `--pretty-print` (#392)
